title: Kigali Online Payments Meetup
description: The Online Payments Meetup is an informal event to discuss the state and the future of payments in Rwanda and the whole continent.

url: http://brianmaierjr.github.com/long-haul
baseurl: "/long-haul"
paginate_path: "posts/page:num/"

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 10

navigation:
 - title: Home
   url: /index
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   email: hello@micahelbumann.com

stamplay: 
  app_id: 'kigalipaymentmeetup'

google_analytics: ""
